defaults: &defaults
  host: 'localhost:3000'

development:
  <<: *defaults
  host: 'localhost:3000'
  facebook:
    APP_ID: '1441124259474236'
    APP_SECRET_ID: '93b2c340b13ed77606c4d2b5129b9381'
  gmail:
    APP_ID: '1044996955605-gr0lvpu3ejbf4jlc2ghh3ut3vt78h8er.apps.googleusercontent.com'
    APP_SECRET_ID: 'EiJx0W5quLsbidRx-n2Y6AyE'
  aws:
    bucket: 'xerofit-dev'
    access_key_id: 'AKIAJQO4FI77C73MNHRA'
    secret_access_key: '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'

test:
  <<: *defaults

production:
  <<: *defaults
  host: 'trainers.xerofit.com/'
  facebook:
    APP_ID: '1495361647345455'
    APP_SECRET_ID: '1d605640672025bd2f184072a150ea89'
  gmail:
    APP_ID: '1055695204606-kas71rqieg1e0fsguvhekum2eo4lgd4g.apps.googleusercontent.com'
    APP_SECRET_ID: 'ZJha_iPwdCt0KzQMbkYEzK9I'
  aws:
    bucket: 'xerofit-development'
    access_key_id: 'AKIAJQO4FI77C73MNHRA'
    secret_access_key: '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'